# This workflow will build a .NET project 
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net
name: .NET
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
jobs:
  build:
    runs-on: windows-2019
    steps:
    - uses: actions/checkout@v2
    
    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1
    
    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1.0.5
      
    - name: setup-msbuild
      uses: microsoft/setup-msbuild@v1.1
    
    - name: Restore Packages
      run: nuget restore cex2string.sln
    
    - name: Build solution
      run: msbuild cex2string.sln -t:rebuild -property:Configuration=Release -property:AllowUnsafeBlocks=True

    - uses: actions/upload-artifact@v3
      if: github.ref == 'refs/heads/master' || startsWith(github.ref, 'refs/tags/')
      with:
        name: cex2string
        path: cex2string
